name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set gradle permissions
        run: sudo chmod +x ./gradlew
      - name: Download dependencies
        run: |
          ./gradlew dependencies
      - name: Build debug
        run: |
          ./gradlew assembleRelease
  deploy:
    runs-on: [ubuntu-latest]
    needs: build
    steps:
      - name: KEY
        env:
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
          GPR_USER: ${{ secrets.GPR_USER }}
      - name: Publish
        run: ./gradlew publish
